/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package interfaces;

import bancodados.FuncionarioBD;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.border.Border;
import modelo.classes.Funcionario;

/**
 *
 * @author Adonias
 */
public class TelaLogin extends javax.swing.JDialog {

     FuncionarioBD conexaoParaFuncionarios = new FuncionarioBD();
     // Criando uma lista de funcionarios
     ArrayList<Funcionario> listaFuncionarios=new ArrayList();
     int cont;
     boolean logado = false;
     String permissaoUsuario;
     String nomeUsuario;
     
    /**
     * Creates new form TelaLogin
     */
    public TelaLogin(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
    
        initComponents();
        pnFundoLogin.setBackground(new Color(121,15,1));
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(new Color(255, 255, 0));
    }

    /***
     * METODO PARA VERIFICAR SE NOME DE USUARIO E SENHA ESTÃO CADASTRADOS
     * PARA ACESSAR AO SISTEMA E O TIPO DE USUARIO - ADMINISTRADOR - USUARIO
     */
    public void logar()
    {
        String senha = "";
        for (int i = 0; i < pfSenha.getPassword().length; i++) {
            senha += pfSenha.getPassword()[i];
        }
        if (confirmarUsuario(tfUsuario.getText().trim(), senha.trim())) {
            JOptionPane.showMessageDialog(rootPane, "<html><b><center>     Bem Vindo!     </center></b></html>", "Iniciando Sistema", 0);
            String nomeArq = "ultimoUsuario.txt";
            logado = true;
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(rootPane, "<html><b>Usuário ou Senha inválidos,<br>Tente novamente</b></html>","Erro!", 0);
            limparCampos();
            tfUsuario.requestFocus();
            logado = false;
        }
    }
    
    public void limparCampos()
    {
        tfUsuario.setText("");
        pfSenha.setText("");
        btEntrar.setBackground(Color.WHITE);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnFundoLogin = new javax.swing.JPanel();
        lbLogo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pfSenha = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        btEntrar = new javax.swing.JButton();
        btEsqueciSenha = new javax.swing.JButton();
        btFechar = new javax.swing.JButton();
        tfUsuario = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("SISTEMA QUICKER - LOGIN");
        setBackground(new java.awt.Color(255, 255, 0));

        lbLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logoBuzios.jpg"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 0, 28)); // NOI18N
        jLabel1.setText("Login");

        pfSenha.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        pfSenha.setToolTipText("INSIRA SUA SENHA.");
        pfSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pfSenhaKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 28)); // NOI18N
        jLabel3.setText("Senha");

        btEntrar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btEntrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones-pequenos-3/Unlock.png"))); // NOI18N
        btEntrar.setText("Entrar");
        btEntrar.setToolTipText("ACESSAR SISTEMA QUICKER");
        btEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEntrarActionPerformed(evt);
            }
        });

        btEsqueciSenha.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btEsqueciSenha.setText("Esqueci Minha Senha");
        btEsqueciSenha.setToolTipText("SOLICITAT NOVA SENHA AO ADMINISTRADOR");
        btEsqueciSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEsqueciSenhaActionPerformed(evt);
            }
        });

        btFechar.setBackground(new java.awt.Color(255, 255, 255));
        btFechar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btFechar.setForeground(new java.awt.Color(255, 0, 51));
        btFechar.setText("<html>SAIR</html>");
        btFechar.setToolTipText("FECHAR SISTEMA QUICKER");
        btFechar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFecharActionPerformed(evt);
            }
        });

        tfUsuario.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N

        javax.swing.GroupLayout pnFundoLoginLayout = new javax.swing.GroupLayout(pnFundoLogin);
        pnFundoLogin.setLayout(pnFundoLoginLayout);
        pnFundoLoginLayout.setHorizontalGroup(
            pnFundoLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnFundoLoginLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(pnFundoLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnFundoLoginLayout.createSequentialGroup()
                        .addComponent(btEntrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btEsqueciSenha))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnFundoLoginLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnFundoLoginLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(pfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(btFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnFundoLoginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
        pnFundoLoginLayout.setVerticalGroup(
            pnFundoLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnFundoLoginLayout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(lbLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnFundoLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnFundoLoginLayout.createSequentialGroup()
                        .addGroup(pnFundoLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnFundoLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(pfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnFundoLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btEntrar)
                            .addComponent(btEsqueciSenha))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnFundoLoginLayout.createSequentialGroup()
                        .addComponent(btFechar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnFundoLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnFundoLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEntrarActionPerformed
        // TODO add your handling code here:
        logar();
    }//GEN-LAST:event_btEntrarActionPerformed

    /**
     * Confirmando se o Usuário existe
     * @param login
     * @param senha
     * @return
     */
    public boolean confirmarUsuario(String login, String senha) {
        for (int i = 0; i < listaFuncionarios.size(); i++) {
            if (login.equals(listaFuncionarios.get(i).getNomeUsuario()) && senha.equals(listaFuncionarios.get(i).getSenhaFuncionario())) {
                permissaoUsuario = listaFuncionarios.get(i).getPermissaoFuncionario();
                return true;
            }
        }
        return false;
    }
    private void btEsqueciSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEsqueciSenhaActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "BANCO DE DADOS QUICKER.", "LEMBRETE SENHA", 3);
    }//GEN-LAST:event_btEsqueciSenhaActionPerformed

    private void btFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFecharActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btFecharActionPerformed

    private void pfSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pfSenhaKeyPressed
        // TODO add your handling code here:
        if(pfSenha.getCaretPosition()==9)
        {
            btEntrar.requestFocus();
            btEntrar.setBackground(Color.green);
        }
    }//GEN-LAST:event_pfSenhaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaLogin dialog = new TelaLogin(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEntrar;
    private javax.swing.JButton btEsqueciSenha;
    private javax.swing.JButton btFechar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JPasswordField pfSenha;
    private javax.swing.JPanel pnFundoLogin;
    private javax.swing.JTextField tfUsuario;
    // End of variables declaration//GEN-END:variables
}