/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package interfaces;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author alunov2
 */
public class TelaVendaDinheiro extends javax.swing.JDialog {

    /**
     * Creates new form TelaVendaDinheiro
     */
    public TelaVendaDinheiro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ftfValorTotalVendaDin = new javax.swing.JFormattedTextField();
        ftfValorRecebidoDin = new javax.swing.JFormattedTextField();
        ftfValorTrocoDin = new javax.swing.JFormattedTextField();
        btFinalizarVendaDinheiro = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setTitle("PDV - VENDA EM DINHEIRO");
        setAlwaysOnTop(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("VALOR TOTAL ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("VALOR RECEBIDO");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("VALOR TROCO");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("R$");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("R$");

        ftfValorRecebidoDin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftfValorRecebidoDinActionPerformed(evt);
            }
        });
        ftfValorRecebidoDin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ftfValorRecebidoDinFocusLost(evt);
            }
        });

        ftfValorTrocoDin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));

        btFinalizarVendaDinheiro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btFinalizarVendaDinheiro.setText("Finalizar Venda");
        btFinalizarVendaDinheiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFinalizarVendaDinheiroActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar Venda");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(128, 158, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btFinalizarVendaDinheiro)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(ftfValorTotalVendaDin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                .addComponent(ftfValorRecebidoDin, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ftfValorTrocoDin, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(ftfValorTotalVendaDin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(ftfValorRecebidoDin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ftfValorTrocoDin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btFinalizarVendaDinheiro)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ftfValorRecebidoDinFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftfValorRecebidoDinFocusLost
        // TODO add your handling code here:
        // VERIFICANDO SE VALOR RECEBIDO E MENOR QUE O VALOR TOTAL
        double valorTotalVenda=Double.parseDouble(ftfValorTotalVendaDin.getText().replace(",", "."));
        double valorRecebido=Double.parseDouble(ftfValorRecebidoDin.getText().replace(",", "."));
        if(valorRecebido<valorTotalVenda)
        {
            JOptionPane.showMessageDialog(this, "VERIFIQUE O VALOR TOTAL E\nVALOR RECEBIDO!");
            ftfValorRecebidoDin.setBackground(Color.RED);
            ftfValorRecebidoDin.requestFocus();
            ftfValorTotalVendaDin.setBackground(Color.yellow);
            btFinalizarVendaDinheiro.setEnabled(false);
        }else
        {
            ftfValorTotalVendaDin.setBackground(Color.white);
            ftfValorRecebidoDin.setBackground(Color.white);
            // VERIFICANDO VALOR DO TROCO
            double total=Double.parseDouble(ftfValorTotalVendaDin.getText().replace(",", "."));
            double recebido=Double.parseDouble(ftfValorRecebidoDin.getText().replace(",", "."));
            double troco=(total-recebido);
                if(troco<0)
                {
                    troco=(troco*(-1));
                }
                    ftfValorTrocoDin.setValue(troco);
                    btFinalizarVendaDinheiro.setEnabled(true);
        }
    }//GEN-LAST:event_ftfValorRecebidoDinFocusLost

    private void ftfValorRecebidoDinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftfValorRecebidoDinActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ftfValorRecebidoDinActionPerformed

    private void btFinalizarVendaDinheiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFinalizarVendaDinheiroActionPerformed
        // TODO add your handling code here:
        this.setVisible(false); 
    }//GEN-LAST:event_btFinalizarVendaDinheiroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVendaDinheiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVendaDinheiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVendaDinheiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVendaDinheiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaVendaDinheiro dialog = new TelaVendaDinheiro(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btFinalizarVendaDinheiro;
    private javax.swing.JFormattedTextField ftfValorRecebidoDin;
    private javax.swing.JFormattedTextField ftfValorTotalVendaDin;
    private javax.swing.JFormattedTextField ftfValorTrocoDin;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
